spring:
  application:
    name: crypto-exchange
  datasource:
    url: jdbc:h2:mem:crypto
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
  h2:
    console.enabled: true

rest:
  baseuri:
    binance: https://api.binance.com/api/v3/ticker/bookTicker
    huobi: https://api.huobi.pro/market/tickers

server:
  port: 8081