spring:
  application:
    name: crypto-exchange
  datasource:
    url: jdbc:h2:mem:crypto
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  jpa:
    defer-datasource-initialization: true

rest:
  baseuri:
    binance: https://api.binance.com/api/v3/ticker/bookTicker
    huobi: https://api.huobi.pro/market/tickers

app:
  schedule:
    call-price:
      cron: "*/5 * * * * *"

server:
  port: 8081